spring:
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: WEB-INF/**
  freemarker:
    cache: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  redis:
    host: 182.92.78.180
    port: 6379
    #password: root
    database: 1
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
    timeout: 3000

  datasource:
    url: jdbc:mysql://182.92.78.180:3306/film_review?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: Miaobu123456_
    driver-class-name: com.mysql.cj.jdbc.Driver

# 控制台打印sql语句
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 8081